"""Shared store protocol for MemoryStore and FirestoreStore."""

from __future__ import annotations

from typing import Any, Protocol

from app.models.approval import ApprovalRequest
from app.models.incident import Incident
from app.models.inventory import InventoryItem
from app.models.machine import Machine
from app.models.telemetry import TelemetrySample
from app.models.work_order import WorkOrder


class DomainStore(Protocol):
    def upsert_machine(self, machine: Machine) -> Machine: ...

    def get_machine(self, machine_id: str) -> Machine | None: ...

    def add_telemetry(self, sample: TelemetrySample) -> TelemetrySample: ...

    def get_telemetry_for_machine(self, machine_id: str) -> list[TelemetrySample]: ...

    def add_incident(self, incident: Incident) -> Incident: ...

    def get_incident(self, incident_id: str) -> Incident | None: ...

    def get_open_incident_for_machine(self, machine_id: str) -> Incident | None: ...

    def list_incidents(self) -> list[Incident]: ...

    def upsert_work_order(self, work_order: WorkOrder) -> WorkOrder: ...

    def list_work_orders(self) -> list[WorkOrder]: ...

    def get_work_order(self, work_order_id: str) -> WorkOrder | None: ...

    def upsert_inventory_item(self, item: InventoryItem) -> InventoryItem: ...

    def list_inventory(self) -> list[InventoryItem]: ...

    def search_inventory(self, query: str) -> list[InventoryItem]: ...

    def set_maintenance_history(
        self, machine_id: str, entries: list[dict[str, Any]]
    ) -> None: ...

    def get_maintenance_history(self, machine_id: str) -> list[dict[str, Any]]: ...

    def set_manual_sections(
        self, machine_id: str, sections: list[dict[str, Any]]
    ) -> None: ...

    def search_manual(self, machine_id: str, query: str) -> list[dict[str, Any]]: ...

    def has_manual(self, machine_id: str) -> bool: ...

    def add_notification(self, notification: dict[str, Any]) -> dict[str, Any]: ...

    def list_notifications(self) -> list[dict[str, Any]]: ...

    def add_agent_action(self, action: dict[str, Any]) -> dict[str, Any]: ...

    def list_agent_actions(self) -> list[dict[str, Any]]: ...

    def upsert_approval(self, approval: ApprovalRequest) -> ApprovalRequest: ...

    def get_approval(self, approval_id: str) -> ApprovalRequest | None: ...

    def list_approvals(self) -> list[ApprovalRequest]: ...

    def clear(self) -> None: ...
